### ISSUE TITLE
Morning Session 4/11

### ISSUE THREAD

**Issue by Fig77** [Fig77/Gradients-Project#14]

**Comment by TashfeenRao** [comment]
You did fantastic job. 
code is clean.
css classes techniques are good.
even i learn some styling

**Comment by Rhelli** [comment]
- You could use more complex CSS selectors to avoid having to reuse some class and id names in your HTML. Eg:

   "nav-ul-li default-li border-color-69 default-flex-container";

    Your could have just written:

    ".ul-default-nav > li"

     Which would have selected all li children of the .ul-default-nav parent.

- These ^ 4 classes that are applied to each navbar element could all be condensed into one class.

- Colors seem to have their own classes when they can be integrated into other existing classes.

- I saw you were using " background-position: center 101%;". A good way to center items in a div or a page is to use the following: 

    "position: relative; left: 50%; transform: translateX(-50%);" 

This works for left/ right centering. The same can also be done with "top: 50%" and transform: translateY(-50%);" for top to bottom as well, or both can be applied at the same time.

Overall, however, the page looks great! Looks exactly like the real thing and I would have thought twice! Good work!
